image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install

build_job:
  image: docker:stable
  stage: build
  # Remove
  services:
    - docker:dind
  before_script:
  
    # Let's install Docker
    # - curl https://get.docker.com/ | bash

    - cd docker-monolith
    - docker build -t reddit_app:latest .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag reddit_app:latest $DOCKER_USERNAME/reddit_app:1.0
    - docker push $USERNAME/reddit_app:1.0
  script:
    # Let's build a container
    - echo 'Building'
    # - cd docker-monolith
    # - ps -aux | grep docker
    # - docker build -t reddit_app:latest .
    # - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    # - docker tag reddit_app:latest $USERNAME/reddit_app:1.0
    # - docker push $USERNAME/reddit_app:1.0

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb 

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch_review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

branch_start_vm:
  stage: review
  before_script:
    # Let's assign variables
    - echo $GCP_KEY > ~/gcloud-service-key.json
    - export GCP_KEY_PATH=~/gcloud-service-key.json
    # Lets's install gcloud SDK
    - curl https://sdk.cloud.google.com | bash
    - source /root/google-cloud-sdk/path.bash.inc
    - gcloud auth activate-service-account --key-file=$GCP_KEY_PATH
  script:
    # Let's install Docker & Docker-machine
    - curl https://get.docker.com/ | bash
    - docker -v
    - base=https://github.com/docker/machine/releases/download/v0.16.0 &&
      curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
      install /tmp/docker-machine /usr/local/bin/docker-machine
    # Let's start a machine and deploy container
    - docker-machine create --driver google 
      --google-machine-type f1-micro
      --google-zone europe-west1-b 
      --google-disk-size 10
      --google-machine-image ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
      --google-project $GCP_PROJECT
      ${CI_COMMIT_REF_SLUG}

  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

delete_review_vm:
  stage: review
  before_script:
    # Let's assign variables
    - echo $GCP_KEY > ~/gcloud-service-key.json
    - export GCP_KEY_PATH=~/gcloud-service-key.json
    # Lets's install gcloud SDK
    - curl https://sdk.cloud.google.com | bash
    - source /root/google-cloud-sdk/path.bash.inc
    - gcloud auth activate-service-account --key-file=$GCP_KEY_PATH
  script:
    # Let's delete the machine
    - gcloud compute instances delete ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
  when: manual
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo "Deploy"
  environment:
    name: stage
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo "Deploy"
  environment:
    name: production
    url: http://example.com
