global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#konstantin_solomin'
